# Generated by Django 3.0 on 2019-12-28 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReturnOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50)),
                ('product_type', models.CharField(max_length=50)),
                ('user_email', models.EmailField(max_length=250)),
                ('phone_no', models.CharField(max_length=10)),
                ('description', models.TextField()),
            ],
        ),
    ]
